VL - Proposed Models
eahs/FBLASocialApp-Backend pull request #1
Opened 2020-10-22 02:43 UTC by vinniehat

2020-10-23 13:08 UTC, tanczosm requested changes
Fix these issues and I will review again

2020-10-23 13:08 UTC, tanczosm commented on ADSBackend/Models/Member.cs
> +        [Required]
Add [JsonIgnore] to Password and Password Salt

2020-10-23 13:08 UTC, tanczosm commented on ADSBackend/Models/Comment.cs
> +		public int ParentCommentId { get; set; }
add: public Comment Parent {get; set; }

2020-10-23 13:08 UTC, tanczosm commented on ADSBackend/Models/ChatMessage.cs
> +		public Member Author { get; set; }
add public int AuthorId {get; set;}

2020-10-23 13:08 UTC, tanczosm commented on ADSBackend/Models/ChatMessage.cs
> +		public Member To { get; set; }
add public int ToId {get; set; }

2020-10-23 13:08 UTC, tanczosm commented on ADSBackend/Models/ChatMessage.cs
> +		public bool isDeleted { get; set; } = false;
Capitalize IsDeleted

2020-10-23 13:08 UTC, tanczosm commented on ADSBackend/Models/ChatSession.cs
> +		public DateTime LastMessageSentAt { get; set; }
Add [NotMapped] 
public Message LastMessage { get; set; }

2020-10-23 13:08 UTC, tanczosm commented on ADSBackend/Models/ChatSession.cs
> +		public Member Member1 { get; set; }
Remove Member1, Member2, etc.
Add public List<ChatMember> ChatMembers {get; set;}

2020-10-23 13:08 UTC, tanczosm commented on ADSBackend/Models/Post.cs
> +		public bool isDeleted { get; set; } = false;
Rename isDeleted to IsDeleted

2020-10-23 13:08 UTC, tanczosm commented on ADSBackend/Models/Post.cs
> +
Add
public int FavoriteCount { get; set; }
public bool IsFeatured { get; set; }
[NotMapped]
public bool IsFavorite { get; set; }

2020-10-23 19:49 UTC, vinniehat commented on ADSBackend/Models/Comment.cs
> +		public int ParentCommentId { get; set; }
Would we need to have a ParentId also?

2020-10-23 19:55 UTC, vinniehat commented on ADSBackend/Models/Post.cs
> +		public bool isDeleted { get; set; } = false;
Also changed IsMachinePost

2020-10-24 02:49 UTC, tanczosm commented on ADSBackend/Models/Comment.cs
> +		public int ParentCommentId { get; set; }
It's there as ParentCommentId

2020-10-24 03:00 UTC, tanczosm requested changes
Looks better.  Just a few more issues to address before we can merge.

2020-10-24 03:00 UTC, tanczosm commented on ADSBackend/Models/ChatSession.cs
> +		public int SessionId { get; set; }
Rename SessionId to ChatSessionId

2020-10-24 03:00 UTC, tanczosm commented on ADSBackend/Models/ChatSession.cs
> +		public Session Session { get; set; }
Get rid of the Session line

2020-10-24 03:00 UTC, tanczosm commented on ADSBackend/Models/ChatSession.cs
> +		public List<Member> ChatMembers { get; set; }
Unfortunately you can't do this.  Nowhere in the database will it store the list of members that are part of the chat session.  A single solitary member does not have any attachment in the Member class to a particular ChatSession so you're going to need another class to act as the glue that tracks which members belong to which chat sessions. 
Instead, create a new class like this:

ChatSessionMember
{
public int ChatSessionId {get; set;}
public ChatSession ChatSession {get; set;}
public int MemberId {get; set;}
public Member Member {get; set;}
}

And then change this line to:
public List<ChatSessionMember> ChatMembers {get; set;}

2020-10-24 03:25 UTC, vinniehat commented on ADSBackend/Models/Comment.cs
> +		public int ParentCommentId { get; set; }
Oh my gosh I'm I apologize 🤦 ~ it's been a long day for me. I apologize about that let me submit the commit and finish that up!

2020-10-24 04:06 UTC, merged